Create Company
portal-solus/backend pull request #18
Opened 2021-06-24 14:45 UTC by jooaodanieel

Seguindo o _tracer bullet_ de Disciplinas

Signed-off-by: João Daniel <jotaf.daniel@gmail.com>

2021-06-26 16:46 UTC, T-Guerrero requested changes

2021-06-26 16:46 UTC, T-Guerrero commented on app/controllers/company_controller.rb
> +class CompanyController < ApplicationController
Não sei se real tem algum impacto no funcionamento do Rails, mas eu realmente queria seguir a convenção de deixar o nome do controller no plural

2021-06-26 16:46 UTC, T-Guerrero commented on app/models/company.rb
> +  field :active, type: Boolean
Olhei no front e a gente nem se quer muda o valor desses dois (eles são sempre true). Pq a gente não corta?

2021-06-26 16:46 UTC, T-Guerrero commented on app/models/company.rb
> +  validates :name, :year, :emails, :description, :incubated, :ecosystems, :services, :address,
Faltou validar unicidade do nome

2021-06-26 16:46 UTC, T-Guerrero commented on app/models/company.rb
> +  field :address, type: Hash
Faltou validação de município

2021-06-26 16:46 UTC, T-Guerrero commented on app/models/company.rb
> +  field :phones, type: Array
Não vamos validar formato do telefone no back?

2021-06-26 16:46 UTC, T-Guerrero commented on app/models/company.rb
> +        phones: row[6].split(';'),
O Front tem um método de formatação do telefone, não vamos mais usar?

2021-06-26 16:46 UTC, T-Guerrero commented on app/models/company.rb
> +        companySize: ['Microempresa']
Dado hardcodado sem método de definição

2021-06-26 16:46 UTC, T-Guerrero commented on app/services/get_companies_service.rb
> +    raw_disciplines.each_with_index do |row, index|
Nomes errados

2021-06-26 18:04 UTC, jooaodanieel commented on app/controllers/company_controller.rb
> +class CompanyController < ApplicationController
Eu mando uma correção disso num PR dedicado, pode ser?

2021-06-26 18:04 UTC, jooaodanieel commented on app/models/company.rb
> +  field :active, type: Boolean
Acho que precisamos discutir com a auspin

2021-06-26 18:05 UTC, jooaodanieel commented on app/services/get_companies_service.rb
> +    raw_disciplines.each_with_index do |row, index|
Maldito ctrl+c, ctrl-v 🤦🏼

2021-06-26 18:05 UTC, jooaodanieel commented
@T-Guerrero sobre as validações, vou adicioná-las, bem como as formatações

2021-06-26 19:39 UTC, jooaodanieel commented on app/models/company.rb
> +  validates :name, :year, :emails, :description, :incubated, :ecosystems, :services, :address,
Não coloquei isso porque acho que vale deixar "na confiança"

2021-06-26 19:46 UTC, T-Guerrero commented on app/models/company.rb
> +  validates :name, :year, :emails, :description, :incubated, :ecosystems, :services, :address,
@jooaodanieel No meu ver seria bom ter, até pq a gente já teve caso de empresa duplicada

2021-06-26 20:02 UTC, jooaodanieel commented on app/models/company.rb
> +  validates :name, :year, :emails, :description, :incubated, :ecosystems, :services, :address,
@T-Guerrero adicionei o uniqueness mas agora o CI quebra porque falta um mongodb rodando lá.
Pode ignorar isso temporariamente, porque vai precisar adicionar configuração ao CI -- acho que é outro PR

2021-06-26 23:46 UTC, T-Guerrero requested changes

2021-06-26 23:46 UTC, T-Guerrero commented on app/models/company.rb
> +    return row[20] if row[20] == 'Unicórnio'
A empresa ser unicórnio não é excludente de ela ser Microempresa, pequena empresa, etc. Aqui você retorna se já for Unicórnio sem antes adicionar a outra classificação no array

2021-06-28 17:59 UTC, T-Guerrero approved these changes

2021-06-29 22:48 UTC, luizcarlosdk approved these changes

2021-06-29 23:34 UTC, merged